"""empty message

Revision ID: 12c18f3d81e7
Revises: None
Create Date: 2015-09-13 14:06:48.647746

"""

# revision identifiers, used by Alembic.
revision = '12c18f3d81e7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=255), nullable=False),
        sa.Column('password', sa.VARCHAR(length=255), nullable=False),
        sa.Column('role', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
